version: "3.9"

services:

  php80-cli:
    build: ./php80-cli/
    volumes:
      - ..:/app
      - ../logs:/var/log/xdebug
    working_dir: /app

  php81-cli:
    image: php:8.1-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php82-cli:
    image: php:8.2-cli
    volumes:
      - ..:/app/
    working_dir: /app
