name: "Test"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:

  phpstan:
    name: "PHPStan static analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.2"
    steps:
      - uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
      - uses: "actions/checkout@v2"
      - uses: "php-actions/composer@v1"
      - run: "vendor/bin/phpstan analyse"

  unit:
    name: "PHPUnit unit tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - uses: "shivammathur/setup-php@2.9.0"
        with:
          php-version: "${{ matrix.php-version }}"
      - uses: "actions/checkout@v2"
      - uses: "php-actions/composer@v1"
      - run: "vendor/bin/phpunit"
